# Beverley Sun
# bsun448

NEXTBLOCKNUM_START = 0
NEXTBLOCKNUM_END = 1
MODE_START = 1
MODE_END = 3
UID_START = 3
UID_END = 5
GID_START = 5
GID_END = 7
NLINKS_START = 7
NLINKS_END = 8
SIZE_START = 8
SIZE_END = 10
CTIME_START = 10
CTIME_END = 14
MTIME_START = 14
MTIME_END = 18
ATIME_START = 18
ATIME_END = 22
NAME_START = 22
NAME_END = 38
LOCATION_START = 38
LOCATION_END = 39
DATA_START = 39
DATA_END = 64

OVERFLOW_DATA_START = 1
OVERFLOW_DATA_END = 64